name: Testing

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.7]
        
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          pip install torch
          ls ./
      - name: Testing
        run: |
          PYTHONPATH=tests/test_simple.py
